// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurante.Web.Data;

#nullable disable

namespace Restaurante.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261007055001_Categoria_Plato")]
    partial class Categoria_Plato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurante.Web.Entities.Categorias", b =>
                {
                    b.Property<Guid>("IdCategorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategorias");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Restaurante.Web.Entities.Plato", b =>
                {
                    b.Property<Guid>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdCategorias")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPlato");

                    b.HasIndex("IdCategorias");

                    b.ToTable("Plato");
                });

            modelBuilder.Entity("Restaurante.Web.Entities.Plato", b =>
                {
                    b.HasOne("Restaurante.Web.Entities.Categorias", "Categorias")
                        .WithMany("Plato")
                        .HasForeignKey("IdCategorias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Restaurante.Web.Entities.Categorias", b =>
                {
                    b.Navigation("Plato");
                });
#pragma warning restore 612, 618
        }
    }
}
